class BotoClient:
    def __init__(self) -> None: ...

    async def get_all_tables(self) -> list[str]: ...

    async def read(self, command: str) -> tuple[list[str], list[list[int | str]]]: ...

    async def write(self, command: str) -> None: ...
